repos:
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.17.1
    hooks:
      - id: gersemi
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v19.1.5"
    hooks:
      - id: clang-format
        args: [-i]
